version: '3'

services:
  # backend: api for mytastings app
  backend:
    build:
      context: ./backend
    command: gunicorn mytastings.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  # frontend: interface for mytastings app
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend-build:/frontend/build
  # reverse proxy: nginx
  nginx:
    image: nginx:1.20.0
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  frontend-build:
