# Generated by Django 3.2.3 on 2021-05-24 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('classification', models.CharField(max_length=100, null=True, verbose_name='Classification')),
                ('base', models.CharField(max_length=100, null=True, verbose_name='Base')),
                ('year', models.DateField(null=True, verbose_name='Year')),
                ('degree', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Degree (%)')),
                ('volume', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='Volume (mL)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Price')),
            ],
        ),
    ]
