# Generated by Django 3.2.3 on 2021-05-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('beverages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beverages', to='categories.category'),
        ),
    ]
