# Generated by Django 3.2.3 on 2021-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beverages', '0003_beverage_producer'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='beverages', to='tags.Tag'),
        ),
    ]
