# Generated by Django 3.2.3 on 2021-06-07 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0007_auto_20210607_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2021)], verbose_name='Year'),
        ),
    ]
