# Generated by Django 3.2.3 on 2021-06-07 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0008_alter_beverage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)], verbose_name='Volume (mL)'),
        ),
    ]
