# Generated by Django 3.2.3 on 2021-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0010_auto_20210607_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume (mL)'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
