# Generated by Django 3.2.3 on 2021-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_remove_producer_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Region'),
        ),
    ]
