// Global variables
const TASTING_LOADING = 'TASTING_LOADING'
const TASTING_FAIL = 'TASTING_FAIL'
const TASTING_SUCCESS = 'TASTING_SUCCESS'
//const TASTING_CREATE = 'TASTING_CREATE'
//const TASTING_UPDATE = 'TASTING_UPDATE'
//const TASTING_DELETE = 'TASTING_DELETE'


// Export
export {
    TASTING_LOADING,
    TASTING_FAIL,
    TASTING_SUCCESS
    //TASTING_CREATE,
    //TASTING_UPDATE,
    //TASTING_DELETE
}