# Generated by Django 3.2.3 on 2021-05-24 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beverages', '0004_beverage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('appearance', models.CharField(max_length=100, verbose_name='Appearance')),
                ('aroma', models.CharField(max_length=100, verbose_name='Aroma')),
                ('finish', models.CharField(max_length=100, verbose_name='Finish')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beverages.beverage')),
            ],
        ),
    ]
