# Generated by Django 3.2.3 on 2021-05-27 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tastings', '0002_tasting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasting',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
