# Generated by Django 3.2.3 on 2021-06-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0010_auto_20210607_1758'),
        ('tastings', '0004_auto_20210607_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='beverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tastings', to='beverages.beverage'),
        ),
    ]
